export const positionsCandidatesFrontDev = [
  {
    id: 1,
    post: 'Front End Dev',
    seniorty: 'Senior',
    profilePictureURL: 'String',
    fullName: 'Adolfo Martin',
    dateOfBird: '29/03/1969',
    age: 53,
    sex: 'Masculino',
    email: 'amartin@gmail.com',
    deadline: '13/07/2022',
    experience: '11',
    education: 'Secundario',
    salary: 360000,
    remote: true,
    status: 1,
  },
  {
    id: 2,
    post: 'Front End Dev',
    seniorty: 'SemiSenior',
    profilePictureURL: 'String',
    fullName: 'Adrian Braga',
    dateOfBird: '27/01/1972',
    age: 50,
    sex: 'Masculino',
    email: 'abraga@yahoo.com',
    deadline: '13/07/2022',
    experience: '8',
    education: 'Universitario',
    salary: 280000,
    remote: true,
    status: 1,
  },
  {
    id: 3,
    post: 'Front End Dev',
    seniorty: 'Trainee',
    profilePictureURL: 'String',
    fullName: 'Carla Arredondo',
    dateOfBird: '08/02/1988',
    age: 34,
    sex: 'Femenino',
    email: 'carredondo@yahoo.com.ar',
    deadline: '13/07/2022',
    experience: '1',
    education: 'Terciario',
    salary: 120000,
    remote: true,
    status: 1,
  },
  {
    id: 4,
    post: 'Front End Dev',
    seniorty: 'Junior',
    profilePictureURL: 'String',
    fullName: 'Gimena Alvarez',
    dateOfBird: '20/10/1993',
    age: 28,
    sex: 'Femenino',
    email: 'galvarez@gmail.com',
    deadline: '13/07/2022',
    experience: '4',
    education: 'Secundario',
    salary: 200000,
    remote: true,
    status: 1,
  },
  {
    id: 5,
    post: 'Front End Dev',
    seniorty: 'Senior',
    profilePictureURL: 'String',
    fullName: 'Leandro Ambrosio',
    dateOfBird: '29/07/1966',
    age: 55,
    sex: 'Masculino',
    email: 'lambrosio@gmail.com',
    deadline: '13/07/2022',
    experience: '11',
    education: 'Universitario',
    salary: 400000,
    remote: true,
    status: 1,
  },
  {
    id: 6,
    post: 'Front End Dev',
    seniorty: 'SemiSenior',
    profilePictureURL: 'String',
    fullName: 'Nadia Florencio',
    dateOfBird: '04/03/1982',
    age: 40,
    sex: 'Femenino',
    email: 'nflorencio@gmail.com',
    deadline: '13/07/2022',
    experience: '7',
    education: 'Universitario',
    salary: 300000,
    remote: true,
    status: 1,
  },
  {
    id: 7,
    post: 'Front End Dev',
    seniorty: 'Junior',
    profilePictureURL: 'String',
    fullName: 'Rafael Gonzales',
    dateOfBird: '10/10/1981',
    age: 40,
    sex: 'Masculino',
    email: 'rgonzales@gmail.com',
    deadline: '13/07/2022',
    experience: '3',
    education: 'Terciario',
    salary: 230000,
    remote: true,
    status: 1,
  },
  {
    id: 8,
    post: 'Front End Dev',
    seniorty: 'SemiSenior',
    profilePictureURL: 'String',
    fullName: 'Orestes Chena',
    dateOfBird: '16/08/1976',
    age: 45,
    sex: 'Masculino',
    email: 'ochena@yahoo.com',
    deadline: '13/07/2022',
    experience: '8',
    education: 'Terciario',
    salary: 370000,
    remote: true,
    status: 1,
  },
  {
    id: 9,
    post: 'Front End Dev',
    seniorty: 'Trainee',
    profilePictureURL: 'String',
    fullName: 'Patricio Conde',
    dateOfBird: '13/11/1998',
    age: 23,
    sex: 'Masculino',
    email: 'pconde@hotmail.com',
    deadline: '13/07/2022',
    experience: '2',
    education: 'Universitario',
    salary: 180000,
    remote: true,
    status: 1,
  },
  {
    id: 10,
    post: 'Front End Dev',
    seniorty: 'Senior',
    profilePictureURL: 'String',
    fullName: 'Vanesa Aquino',
    dateOfBird: '11/09/1968',
    age: 53,
    sex: 'Femenino',
    email: 'vaquino@hotmail.com',
    deadline: '13/07/2022',
    experience: '10',
    education: 'Terciario',
    salary: 350000,
    remote: true,
    status: 1,
  },
];
